[
  {
    pid: "P0001",
    slug: "rust-casual-combo",
    title: "Rust Casual Combo",
    category: "Combos",
    gender: "Men",
    color: "Rust Orange",
    colorHex: "#b7410e",
    tone: "Warm",
    sizeOptions: ["M", "L", "XL"],
    price: 59.99,
    salePrice: 49.99,
    rating: 4.7,
    reviews: 180,
    isNew: true,
    src: "/images/products/1.jpg",
    gallery: [
      "/images/products/1.jpg",
      "/images/products/1.jpg",
      "/images/products/1.jpg",
    ],
  },
  {
    pid: "P0002",
    slug: "beige-formal-combo",
    title: "Beige Formal Combo",
    category: "Combos",
    gender: "Women",
    color: "Beige",
    colorHex: "#f5f5dc",
    tone: "Neutral",
    sizeOptions: ["S", "M", "L"],
    price: 69.99,
    salePrice: 59.99,
    rating: 4.6,
    reviews: 150,
    isNew: false,
    src: "/images/products/2.jpg",
    gallery: [
      "/images/products/2.jpg",
      "/images/products/2.jpg",
      "/images/products/2.jpg",
    ],
  },
  {
    pid: "P0003",
    slug: "navy-denim-jacket",
    title: "Navy Denim Jacket",
    category: "Jackets",
    gender: "Men",
    color: "Navy Blue",
    colorHex: "#001f3f",
    tone: "Cool",
    sizeOptions: ["M", "L", "XL"],
    price: 89.99,
    salePrice: 74.99,
    rating: 4.8,
    reviews: 240,
    isNew: true,
    src: "/images/products/3.jpg",
    gallery: [
      "/images/products/3.jpg",
      "/images/products/3.jpg",
      "/images/products/3.jpg",
    ],
  },
  {
    pid: "P0004",
    slug: "white-summer-dress",
    title: "White Summer Dress",
    category: "Dresses",
    gender: "Women",
    color: "White",
    colorHex: "#ffffff",
    tone: "Light",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 79.99,
    salePrice: 69.99,
    rating: 4.5,
    reviews: 132,
    isNew: true,
    src: "/images/products/4.jpg",
    gallery: [
      "/images/products/4.jpg",
      "/images/products/4.jpg",
      "/images/products/4.jpg",
    ],
  },
  {
    pid: "P0005",
    slug: "black-leather-jacket",
    title: "Black Leather Jacket",
    category: "Jackets",
    gender: "Men",
    color: "Black",
    colorHex: "#000000",
    tone: "Dark",
    sizeOptions: ["M", "L", "XL"],
    price: 129.99,
    salePrice: 109.99,
    rating: 4.9,
    reviews: 320,
    isNew: false,
    src: "/images/products/5.jpg",
    gallery: [
      "/images/products/5.jpg",
      "/images/products/5.jpg",
      "/images/products/5.jpg",
    ],
  },
  {
    pid: "P0006",
    slug: "olive-cargo-pants",
    title: "Olive Cargo Pants",
    category: "Bottoms",
    gender: "Men",
    color: "Olive Green",
    colorHex: "#708238",
    tone: "Earthy",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 69.99,
    salePrice: 59.99,
    rating: 4.3,
    reviews: 90,
    isNew: false,
    src: "/images/products/6.jpg",
    gallery: [
      "/images/products/6.jpg",
      "/images/products/6.jpg",
      "/images/products/6.jpg",
    ],
  },
  {
    pid: "P0007",
    slug: "pink-floral-top",
    title: "Pink Floral Top",
    category: "Tops",
    gender: "Women",
    color: "Pink",
    colorHex: "#ffc0cb",
    tone: "Soft",
    sizeOptions: ["S", "M", "L"],
    price: 49.99,
    salePrice: 39.99,
    rating: 4.2,
    reviews: 77,
    isNew: true,
    src: "/images/products/7.jpg",
    gallery: [
      "/images/products/7.jpg",
      "/images/products/7.jpg",
      "/images/products/7.jpg",
    ],
  },
  {
    pid: "P0008",
    slug: "gray-office-blazer",
    title: "Gray Office Blazer",
    category: "Formals",
    gender: "Men",
    color: "Gray",
    colorHex: "#808080",
    tone: "Neutral",
    sizeOptions: ["M", "L", "XL"],
    price: 99.99,
    salePrice: 89.99,
    rating: 4.6,
    reviews: 175,
    isNew: false,
    src: "/images/products/8.jpg",
    gallery: [
      "/images/products/8.jpg",
      "/images/products/8.jpg",
      "/images/products/8.jpg",
    ],
  },
  {
    pid: "P0009",
    slug: "emerald-party-gown",
    title: "Emerald Party Gown",
    category: "Dresses",
    gender: "Women",
    color: "Emerald Green",
    colorHex: "#50c878",
    tone: "Vibrant",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 149.99,
    salePrice: 129.99,
    rating: 4.9,
    reviews: 290,
    isNew: true,
    src: "/images/products/9.jpg",
    gallery: [
      "/images/products/9.jpg",
      "/images/products/9.jpg",
      "/images/products/9.jpg",
    ],
  },
  {
    pid: "P0010",
    slug: "white-cotton-shirt",
    title: "White Cotton Shirt",
    category: "Shirts",
    gender: "Men",
    color: "White",
    colorHex: "#ffffff",
    tone: "Light",
    sizeOptions: ["M", "L", "XL"],
    price: 49.99,
    salePrice: 39.99,
    rating: 4.5,
    reviews: 210,
    isNew: false,
    src: "/images/products/10.jpg",
    gallery: [
      "/images/products/10.jpg",
      "/images/products/10.jpg",
      "/images/products/10.jpg",
    ],
  },
  {
    pid: "P0011",
    slug: "navy-pencil-skirt",
    title: "Navy Pencil Skirt",
    category: "Bottoms",
    gender: "Women",
    color: "Navy Blue",
    colorHex: "#001f3f",
    tone: "Cool",
    sizeOptions: ["S", "M", "L"],
    price: 59.99,
    salePrice: 49.99,
    rating: 4.4,
    reviews: 95,
    isNew: false,
    src: "/images/products/11.jpg",
    gallery: [
      "/images/products/11.jpg",
      "/images/products/11.jpg",
      "/images/products/11.jpg",
    ],
  },
  {
    pid: "P0012",
    slug: "brown-suede-boots",
    title: "Brown Suede Boots",
    category: "Footwear",
    gender: "Men",
    color: "Brown",
    colorHex: "#654321",
    tone: "Warm",
    sizeOptions: ["7", "8", "9", "10"],
    price: 119.99,
    salePrice: 99.99,
    rating: 4.8,
    reviews: 260,
    isNew: true,
    src: "/images/products/12.jpg",
    gallery: [
      "/images/products/12.jpg",
      "/images/products/12.jpg",
      "/images/products/12.jpg",
    ],
  },
  {
    pid: "P0013",
    slug: "cream-knit-sweater",
    title: "Cream Knit Sweater",
    category: "Sweaters",
    gender: "Women",
    color: "Cream",
    colorHex: "#fffdd0",
    tone: "Soft",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 79.99,
    salePrice: 69.99,
    rating: 4.6,
    reviews: 140,
    isNew: true,
    src: "/images/products/13.jpg",
    gallery: [
      "/images/products/13.jpg",
      "/images/products/13.jpg",
      "/images/products/13.jpg",
    ],
  },
  {
    pid: "P0014",
    slug: "charcoal-slim-trousers",
    title: "Charcoal Slim Trousers",
    category: "Formals",
    gender: "Men",
    color: "Charcoal",
    colorHex: "#36454f",
    tone: "Neutral",
    sizeOptions: ["M", "L", "XL"],
    price: 89.99,
    salePrice: 79.99,
    rating: 4.3,
    reviews: 110,
    isNew: false,
    src: "/images/products/14.jpg",
    gallery: [
      "/images/products/14.jpg",
      "/images/products/14.jpg",
      "/images/products/14.jpg",
    ],
  },
  {
    pid: "P0015",
    slug: "red-party-dress",
    title: "Red Party Dress",
    category: "Dresses",
    gender: "Women",
    color: "Red",
    colorHex: "#ff0000",
    tone: "Bold",
    sizeOptions: ["S", "M", "L"],
    price: 129.99,
    salePrice: 99.99,
    rating: 4.9,
    reviews: 310,
    isNew: true,
    src: "/images/products/15.jpg",
    gallery: [
      "/images/products/15.jpg",
      "/images/products/15.jpg",
      "/images/products/15.jpg",
    ],
  },
  {
    pid: "P0016",
    slug: "blue-casual-jeans",
    title: "Blue Casual Jeans",
    category: "Bottoms",
    gender: "Men",
    color: "Denim Blue",
    colorHex: "#1560bd",
    tone: "Cool",
    sizeOptions: ["M", "L", "XL"],
    price: 79.99,
    salePrice: 69.99,
    rating: 4.5,
    reviews: 190,
    isNew: false,
    src: "/images/products/16.jpg",
    gallery: [
      "/images/products/16.jpg",
      "/images/products/16.jpg",
      "/images/products/16.jpg",
    ],
  },
  {
    pid: "P0017",
    slug: "lavender-knit-cardigan",
    title: "Lavender Knit Cardigan",
    category: "Sweaters",
    gender: "Women",
    color: "Lavender",
    colorHex: "#e6e6fa",
    tone: "Soft",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 69.99,
    salePrice: 59.99,
    rating: 4.7,
    reviews: 130,
    isNew: true,
    src: "/images/products/17.jpg",
    gallery: [
      "/images/products/17.jpg",
      "/images/products/17.jpg",
      "/images/products/17.jpg",
    ],
  },
  {
    pid: "P0018",
    slug: "gray-running-shoes",
    title: "Gray Running Shoes",
    category: "Footwear",
    gender: "Men",
    color: "Gray",
    colorHex: "#808080",
    tone: "Neutral",
    sizeOptions: ["7", "8", "9", "10"],
    price: 99.99,
    salePrice: 84.99,
    rating: 4.8,
    reviews: 250,
    isNew: true,
    src: "/images/products/18.jpg",
    gallery: [
      "/images/products/18.jpg",
      "/images/products/18.jpg",
      "/images/products/18.jpg",
    ],
  },
];
