const productsData = [
  {
    id: "P0001",
    slug: "rust-casual-combo",
    title: "Rust Casual Combo",
    category: "Combos",
    gender: "Men",
    color: "Rust Orange",
    colorHex: "#b7410e",
    tone: "Warm",
    sizeOptions: ["M", "L", "XL"],
    price: 59.99,
    salePrice: 49.99,
    rating: 4.7,
    reviews: 180,
    isNew: true,
    src: "/images/products/1.jpg",
    gallery: [
      "/images/products/1.jpg",
      "/images/products/1.jpg",
      "/images/products/1.jpg",
    ],
  },
  {
    id: "P0002",
    slug: "beige-formal-combo",
    title: "Beige Formal Combo",
    category: "Combos",
    gender: "Women",
    color: "Beige",
    colorHex: "#f5f5dc",
    tone: "Neutral",
    sizeOptions: ["S", "M", "L"],
    price: 69.99,
    salePrice: 59.99,
    rating: 4.6,
    reviews: 150,
    isNew: false,
    src: "/images/products/2.jpg",
    gallery: [
      "/images/products/2.jpg",
      "/images/products/2.jpg",
      "/images/products/2.jpg",
    ],
  },
  {
    id: "P0003",
    slug: "navy-slim-fit-shirt",
    title: "Navy Slim Fit Shirt",
    category: "Shirts",
    gender: "Men",
    color: "Navy Blue",
    colorHex: "#1a2942",
    tone: "Cool",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 45.99,
    salePrice: 39.99,
    rating: 4.8,
    reviews: 210,
    isNew: false,
    src: "/images/products/3.jpg",
    gallery: [
      "/images/products/3.jpg",
      "/images/products/3.jpg",
      "/images/products/3.jpg",
    ],
  },
  {
    id: "P0004",
    slug: "black-classic-blazer",
    title: "Black Classic Blazer",
    category: "Blazers",
    gender: "Men",
    color: "Black",
    colorHex: "#000000",
    tone: "Neutral",
    sizeOptions: ["M", "L", "XL"],
    price: 99.99,
    salePrice: 89.99,
    rating: 4.9,
    reviews: 320,
    isNew: true,
    src: "/images/products/4.jpg",
    gallery: [
      "/images/products/4.jpg",
      "/images/products/4.jpg",
      "/images/products/4.jpg",
    ],
  },
  {
    id: "P0005",
    slug: "white-cotton-shirt",
    title: "White Cotton Shirt",
    category: "Shirts",
    gender: "Men",
    color: "White",
    colorHex: "#ffffff",
    tone: "Neutral",
    sizeOptions: ["S", "M", "L"],
    price: 49.99,
    salePrice: null,
    rating: 4.5,
    reviews: 98,
    isNew: false,
    src: "/images/products/5.jpg",
    gallery: [
      "/images/products/5.jpg",
      "/images/products/5.jpg",
      "/images/products/5.jpg",
    ],
  },
  {
    id: "P0006",
    slug: "olive-utility-jacket",
    title: "Olive Utility Jacket",
    category: "Outerwear",
    gender: "Men",
    color: "Olive Green",
    colorHex: "#808000",
    tone: "Warm",
    sizeOptions: ["M", "L", "XL"],
    price: 89.99,
    salePrice: 74.99,
    rating: 4.4,
    reviews: 160,
    isNew: true,
    src: "/images/products/6.jpg",
    gallery: [
      "/images/products/6.jpg",
      "/images/products/6.jpg",
      "/images/products/6.jpg",
    ],
  },
  {
    id: "P0007",
    slug: "gray-knit-sweater",
    title: "Gray Knit Sweater",
    category: "Sweaters",
    gender: "Women",
    color: "Gray",
    colorHex: "#808080",
    tone: "Cool",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 59.99,
    salePrice: 54.99,
    rating: 4.6,
    reviews: 112,
    isNew: false,
    src: "/images/products/7.jpg",
    gallery: [
      "/images/products/7.jpg",
      "/images/products/7.jpg",
      "/images/products/7.jpg",
    ],
  },
  {
    id: "P0008",
    slug: "cream-wool-coat",
    title: "Cream Wool Coat",
    category: "Outerwear",
    gender: "Women",
    color: "Cream",
    colorHex: "#fffdd0",
    tone: "Neutral",
    sizeOptions: ["S", "M", "L"],
    price: 149.99,
    salePrice: 129.99,
    rating: 4.9,
    reviews: 284,
    isNew: true,
    src: "/images/products/8.jpg",
    gallery: [
      "/images/products/8.jpg",
      "/images/products/8.jpg",
      "/images/products/8.jpg",
    ],
  },
  {
    id: "P0009",
    slug: "charcoal-tailored-pants",
    title: "Charcoal Tailored Pants",
    category: "Pants",
    gender: "Men",
    color: "Charcoal",
    colorHex: "#36454f",
    tone: "Cool",
    sizeOptions: ["M", "L", "XL"],
    price: 69.99,
    salePrice: null,
    rating: 4.7,
    reviews: 142,
    isNew: false,
    src: "/images/products/9.jpg",
    gallery: [
      "/images/products/9.jpg",
      "/images/products/9.jpg",
      "/images/products/9.jpg",
    ],
  },
  {
    id: "P0010",
    slug: "rose-midi-dress",
    title: "Rose Midi Dress",
    category: "Dresses",
    gender: "Women",
    color: "Rose Pink",
    colorHex: "#e9a1a1",
    tone: "Warm",
    sizeOptions: ["S", "M", "L"],
    price: 89.99,
    salePrice: 79.99,
    rating: 4.8,
    reviews: 200,
    isNew: true,
    src: "/images/products/10.jpg",
    gallery: [
      "/images/products/10.jpg",
      "/images/products/10.jpg",
      "/images/products/10.jpg",
    ],
  },
  {
    id: "P0011",
    slug: "sand-linen-shirt",
    title: "Sand Linen Shirt",
    category: "Shirts",
    gender: "Men",
    color: "Sand",
    colorHex: "#c2b280",
    tone: "Neutral",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 55.99,
    salePrice: null,
    rating: 4.4,
    reviews: 133,
    isNew: false,
    src: "/images/products/11.jpg",
    gallery: [
      "/images/products/11.jpg",
      "/images/products/11.jpg",
      "/images/products/11.jpg",
    ],
  },
  {
    id: "P0012",
    slug: "taupe-wide-trousers",
    title: "Taupe Wide Trousers",
    category: "Pants",
    gender: "Women",
    color: "Taupe",
    colorHex: "#b38b6d",
    tone: "Warm",
    sizeOptions: ["S", "M", "L"],
    price: 75.99,
    salePrice: 69.99,
    rating: 4.5,
    reviews: 97,
    isNew: false,
    src: "/images/products/12.jpg",
    gallery: [
      "/images/products/12.jpg",
      "/images/products/12.jpg",
      "/images/products/12.jpg",
    ],
  },
  {
    id: "P0013",
    slug: "black-leather-jacket",
    title: "Black Leather Jacket",
    category: "Outerwear",
    gender: "Men",
    color: "Black",
    colorHex: "#000000",
    tone: "Neutral",
    sizeOptions: ["M", "L", "XL"],
    price: 179.99,
    salePrice: 159.99,
    rating: 4.9,
    reviews: 315,
    isNew: true,
    src: "/images/products/13.jpg",
    gallery: [
      "/images/products/13.jpg",
      "/images/products/13.jpg",
      "/images/products/13.jpg",
    ],
  },
  {
    id: "P0014",
    slug: "ivory-pleated-skirt",
    title: "Ivory Pleated Skirt",
    category: "Skirts",
    gender: "Women",
    color: "Ivory",
    colorHex: "#fffff0",
    tone: "Neutral",
    sizeOptions: ["S", "M", "L"],
    price: 65.99,
    salePrice: null,
    rating: 4.6,
    reviews: 176,
    isNew: false,
    src: "/images/products/14.jpg",
    gallery: [
      "/images/products/14.jpg",
      "/images/products/14.jpg",
      "/images/products/14.jpg",
    ],
  },
  {
    id: "P0015",
    slug: "maroon-satin-dress",
    title: "Maroon Satin Dress",
    category: "Dresses",
    gender: "Women",
    color: "Maroon",
    colorHex: "#800000",
    tone: "Warm",
    sizeOptions: ["S", "M", "L"],
    price: 99.99,
    salePrice: 89.99,
    rating: 4.8,
    reviews: 298,
    isNew: true,
    src: "/images/products/15.jpg",
    gallery: [
      "/images/products/15.jpg",
      "/images/products/15.jpg",
      "/images/products/15.jpg",
    ],
  },
  {
    id: "P0016",
    slug: "ash-oversized-hoodie",
    title: "Ash Oversized Hoodie",
    category: "Sweatshirts",
    gender: "Unisex",
    color: "Ash Gray",
    colorHex: "#b2beb5",
    tone: "Cool",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 79.99,
    salePrice: 69.99,
    rating: 4.7,
    reviews: 188,
    isNew: false,
    src: "/images/products/16.jpg",
    gallery: [
      "/images/products/16.jpg",
      "/images/products/16.jpg",
      "/images/products/16.jpg",
    ],
  },
  {
    id: "P0017",
    slug: "denim-blue-jeans",
    title: "Denim Blue Jeans",
    category: "Pants",
    gender: "Unisex",
    color: "Denim Blue",
    colorHex: "#1f456e",
    tone: "Cool",
    sizeOptions: ["S", "M", "L", "XL"],
    price: 69.99,
    salePrice: null,
    rating: 4.5,
    reviews: 120,
    isNew: false,
    src: "/images/products/17.jpg",
    gallery: [
      "/images/products/17.jpg",
      "/images/products/17.jpg",
      "/images/products/17.jpg",
    ],
  },
  {
    id: "P0018",
    slug: "pearl-white-top",
    title: "Pearl White Top",
    category: "Tops",
    gender: "Women",
    color: "Pearl White",
    colorHex: "#fdfdfd",
    tone: "Neutral",
    sizeOptions: ["S", "M", "L"],
    price: 49.99,
    salePrice: 44.99,
    rating: 4.6,
    reviews: 145,
    isNew: true,
    src: "/images/products/18.jpg",
    gallery: [
      "/images/products/18.jpg",
      "/images/products/18.jpg",
      "/images/products/18.jpg",
    ],
  },
];

export default productsData;
